apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: hub
  namespace: argocd
spec:
  description: Hub cluster apps (in-cluster)
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: development
  namespace: argocd
spec:
  description: Development apps
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://8DC75C7A66ACEF04D7834ACCD553A9AE.gr7.eu-west-1.eks.amazonaws.com
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: production
  namespace: argocd
spec:
  description: Production apps
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://F34A6680DB27ABDBE242F4C47AA534A2.yl4.eu-west-1.eks.amazonaws.com
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: uat
  namespace: argocd
spec:
  description: UAT/staging apps
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: https://238706E93E5AF8032A6F5799E6BAB58F.sk1.eu-west-1.eks.amazonaws.com
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
